### ISSUE TITLE
BBB Recording Pointing "Recording not found" After Integrating BBB with AWS-S3

### ISSUE THREAD

**Issue by MirzaAreebBaig** [rohitcoder/BBB-AWS-S3#1]
Hey,
Installed python-pip, awscli, boto3, python-magic==0.4.15 in /var/bigbluebutton/published/presentation
Done with aws configure
proper BUCKET_NAME in bbb-s3.py
edited S3 url with +meetingId in writing.js
S3 bucket publicly accessible & added script at CORS configuration & done with cron job
but now all the recordings shows Error "Recording not found"

**Comment by rohitcoder** [comment]
Hi @MirzaAreebBaig ,

Before proceeding further, i would like to get more details here.

1. First, check if recordings and files are getting transferred to S3 bucket or not.
2. You need to verify S3 bucket URL is not wrong which you typed under writing.js file.

Few days back i noticed one of the user typed "meetingid" instead of "meetingId" (See capital I here)

Can you please post a screenshot of your writing.js file like this one 

![Editing writing.js](https://raw.githubusercontent.com/rohitcoder/BBB-AWS-S3/master/Screenshot%202020-05-25%20at%2010.56.37%20PM.png)

Alternatively, please check if any uploaded files are accessible by URL without passing any auth-token in URL

For testing this just upload, an image like a.jpg in your bucket and then access it like https://bucketname.s3.amazonaws.com/a.jpg

**Comment by MirzaAreebBaig** [comment]
Yes sure here is the screenshot of S3 & writing.js file
Here is our S3 Screenshot files are not getting transferred to S3
![Capture2](https://user-images.githubusercontent.com/45519744/84866763-cc28d600-b097-11ea-85cd-099bcdf404bc.PNG)

& here is the screenshot of writing.js
![Capture](https://user-images.githubusercontent.com/45519744/84866794-d6e36b00-b097-11ea-8bda-21478ac2f10b.JPG)

Here is the testing url for an image
https://mimberclassesrecording.s3.ap-south-1.amazonaws.com/Capture.JPG

**Comment by rohitcoder** [comment]
@MirzaAreebBaig 

1. First add "/" after amazonaws.com in URL const. It should be like "https://mimber...........amazonaws.com/"+meetingId;

2. And it seems, you downloaded bbb-s3.py folder in root directory, this file "bbb-s3.py" should be under /var/bigbluebutton/published/presentation

**Comment by MirzaAreebBaig** [comment]
1. Added "/" to the url 
![Capture](https://user-images.githubusercontent.com/45519744/84978016-7ad91f00-b149-11ea-87de-301fa2f011d3.JPG)

2. the bbb-s3.py file is in /var/bigbluebutton/published/presentation folder
![Capture](https://user-images.githubusercontent.com/45519744/84978065-a22fec00-b149-11ea-93a0-42ff893d48c0.JPG)


Still the recordings are not getting transferred in S3 & still all recordings point "Recording not found"

**Comment by rohitcoder** [comment]
Now, everything seems good, if you also configured aws configure then now it should work.

you can check it by running this file manually for first time type these commands in terminal

```
sudo su
/usr/bin/python /var/bigbluebutton/published/presentation/bbb-s3.py
```

And post screenshot of the output

**Comment by MirzaAreebBaig** [comment]
Sure please check

![Capture](https://user-images.githubusercontent.com/45519744/85000451-0c5b8780-b170-11ea-974c-101a572dd92e.JPG)

**Comment by rohitcoder** [comment]
@MirzaAreebBaig 

Now, this should work because bbb-s3.py is trying to transfer files to your s3 bucket.

Record a meeting and finish it, and wait for 5 to 7 minutes (BBB takes some time to process raw meetings to finalize it) after 5 to 7 minutes of ending meeting. Run this same command.

/usr/bin/python /var/bigbluebutton/published/presentation/bbb-s3.py

and when it finishes check your s3 bucket, is there any new folder with meeting ID as folder's name.

If it's not there, then you need to check if aws configure is done properly and you have write access keys and id in aws configure variables.

**Comment by MirzaAreebBaig** [comment]
Done with recording & waited till it get published & have run the command
/usr/bin/python /var/bigbluebutton/published/presentation/bbb-s3.py
still the recordings have not been transferred in s3 
& rechecked aws configure variables that seems to be correct

**Comment by rohitcoder** [comment]
@MirzaAreebBaig ,

You need to provide more details here, this works for most of the guys here, and i tested it again, it's working for me.

I'll recommend you to check again your aws credentials, or i can take a look via teamviewer if you are comfortable, else you have to figure it out yourself.

**Comment by MirzaAreebBaig** [comment]
sure please let me know your availability then you can have a look over teamviewer

**Comment by MirzaAreebBaig** [comment]
Hi Rohit,

Now everything seems to be okay in the bbb server

Last time it was showing "Recording not found"

Now the page goes completely blank & title of the page remains loading.

**Comment by rohitcoder** [comment]
>>Now the page goes completely blank & title of the page remains loading.

Which page you are  talking about? can you send me a screenshot, and also attach screenshot from your browser console logs.

**Comment by rohitcoder** [comment]
@MirzaAreebBaig other user also faced this same problem.

We solved it by changing our crontab command please add this in your crontab and let me know if it works for you
```
* * * * * cd /var/bigbluebutton/published/presentation/ && python bbb-s3.py
```

This will execute after every 1 minute (You can changed timings)

Let me know if this works for you

**Comment by MirzaAreebBaig** [comment]
Hey @rohitcoder 

I have added the new command for cron job but still i face the same error blank page while we check any recording here is the screenshot of console

![image](https://user-images.githubusercontent.com/45519744/87418984-4f364100-c5f0-11ea-8415-f064cc264d7d.png)

**Comment by MirzaAreebBaig** [comment]
Hey @rohitcoder  Thanks for this

Now everything is working.

**Comment by rohitcoder** [comment]
Closing this thread as resolved 

Feel free to create or reopen any new issues if needed :)
