### ISSUE TITLE
Playing recordings from S3

### ISSUE THREAD

**Issue by ssh713** [rohitcoder/BBB-AWS-S3#2]
Hi, 
Currently, we play recordings with a server URL like this:
<server>/playback/presentation/2.0/playback.html?meetingId=<meeting-id>

How do we play the recording once it's sent to S3? 
Also does getrecording API work and point to the new URLs

Thanks

**Comment by rohitcoder** [comment]
As per the docs

After updating writing.js files you'll be able to play recordings from the Same URL as you mentioned above.
You just have to update this file
```
$ cd /var/bigbluebutton/playback/presentation/2.0/lib
$ vi writing.js
```
Yes, getrecording API should also work because it's not changing URL of recordings, BTW i didn't checked this, most probably this should also work.

**Comment by ssh713** [comment]
Thanks Rohit,
I am getting this error when run bbb-s3.py script

boto3.exceptions.S3UploadFailedError: Failed to upload /var/bigbluebutton/published/presentation/c701b96b2c7e4f4bb7118ac7bdd5168b3fb5f874-1591792680661/panzooms.xml to schoolx/c701b96b2c7e4f4bb7118ac7bdd5168b3fb5f874-1591792680661/panzooms.xml: An error occurred (IllegalLocationConstraintException) when calling the PutObject operation: The me-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.

**Comment by rohitcoder** [comment]
What is your aws region?

From your error log i can see its somethin like ``me-south-1`` it should be like ``ap-south-1``

Please verify your aws region

**Comment by ssh713** [comment]
Its middle-east (bahrain region)

**Comment by rohitcoder** [comment]
According to this issue https://github.com/aws/aws-cli/issues/3567

Maybe, Your bucket name is not unique? can you try by changing your bucket name to a random name for testing purpose?

**Comment by ssh713** [comment]
Hi Rohit,
I was able to transfer files to AWS and here is my understanding;
Script may not be working if s3 region is other than default: its may be we leave it empty(default) when run s3 config through the console. You may want to check that

1) After I transferred all the files I ran bbb-recording --deleteAll command; and now I cant fetch any recordings information through API
2) I am unable to run the recordings using the old link format e.g.
https://bbb.schoolx.pk/playback/presentation/2.0/playback.html?meetingId=f36e5cf9cbb68355faf1c9807e3ba3ba2d895128-1593680407169 
does not load the recording

Looking forward to hearing from you

**Comment by rohitcoder** [comment]
1. If you are using BBB-API then you should also store copy of your meeting id in a separate table (which is managed by you, not BBB), in this way even after running ``--deleteAll`` you'll be able to fetch Recordings from s3 because you already have meetingID,

2. If you were able to transfer files to s3 then its possible you can fetch those meetings using https://bbb.schoolx.pk/playback/presentation/2.0/playback.html?meetingId=f36e5cf9cbb68355faf1c9807e3ba3ba2d895128-1593680407169

### Verify this
1. In your s3 bucket check if a folder exist with this name ``f36e5cf9cbb68355faf1c9807e3ba3ba2d895128-1593680407169``
2. Now, try to visit https://bbb.schoolx.pk/playback/presentation/2.0/playback.html?meetingId=f36e5cf9cbb68355faf1c9807e3ba3ba2d895128-1593680407169 if it is still not playing your recordings, then there is problem with your installation steps, Verify your writing.js file and you fixed CORS problems for s3

**Comment by rohitcoder** [comment]
@ssh713 

Some users were facing problem with uploading into AWS (Only system files like .aws_config, .profile was getting uploaded and meetings was getting skipped)

Check latest docs i added fix for that.

You should change crontab file's command to execute bbb-s3.py

This is the new command for crontab

```
*/5 * * * * cd /var/bigbluebutton/published/presentation/ && python bbb-s3.py
```

For more check docs

Let me know if this works for you or not, i'll close this issue after 1 or 2 week of not getting any reply.

**Comment by rohitcoder** [comment]
I am closing my this thread as it seems resolved for most of the users and we are not getting replies from your side

Feel free to reopen this thread if needed

**Comment by iFieldSmart-Tech** [comment]
@rohitcoder - It was working fine till now as we were keeping the files on s3 as well as local bbb storage. Now that I started deleting the local files thinking it is working fine, it is unable to play the recordings. Technically, I am still able to play the recordings if I enter the URL as <my/s3/path>/playback/presentation/2.0/playback.html. However, the api getRecordings.php responds with "no recordings found for this meeting". Is there anything I am missing or that's how it is if you delete the files from local storage?
Our page depends upon the response from the getRecordings api and hence want to see if there is any way to fix it.
Thanks in advance

**Comment by rohitcoder** [comment]
@iFieldSmart-Tech 

Try this modified script, and don't delete anything manually after running this script.

BBB, requires metadata.xml and a folder with the only metadata.xml on a local server, so this script deletes all heavy things except metadata.xml and a folder that contains this file.


https://gist.githubusercontent.com/rohitcoder/34779f17b7a8415c0b411800ea6744bb/raw/ce2bc4b370752b52c2e6c5e295f68894ba56d80d/gistfile1.txt

Download the above file, and rename it to bbb-s3.py and configure it, and then try on testing server.

**Comment by iFieldSmart-Tech** [comment]
@rohitcoder Thanks a lot!
Now the code works as expected, there is just one issue though. It uploads the file bbb-s3.py to s3 and deletes it from bbb  server as well.
